<?php

const PROJECT_NAME = '{$PROJECT_NAME}';
const APPLICATION_NAME = '{$APPLICATION_NAME}';
const APPLICATION_USER_NAME = '{$APPLICATION_USER_CAMEL}';

define("PATH_APPLICATION", __DIR__ );
define("PATH_CONTROLLERS", __DIR__ . DIRECTORY_SEPARATOR . 'controllers');

{if $APPLICATION_THEME}
define('URL_THEME', {if $APPLICATION_CDN}URL_{$APPLICATION_CDN_CODE_UPPER} . {/if}'/themes/{$APPLICATION_THEME}');
define('URL_THEME_IMAGES', URL_THEME . '/{$APPLICATION_THEME_IMAGES}');
{/if}