<?php

const PROJECT_NAME = '{$PROJECT_NAME}';

{if $APPLICATION_THEME}
define('URL_THEME', {if $APPLICATION_CDN}URL_{$APPLICATION_CDN_CODE_UPPER} . {/if}'/themes/{$APPLICATION_THEME}');
{/if}
define('URL_THEME_IMAGES', URL_THEME . '/{$APPLICATION_THEME_IMAGES}');