<?php

const PROJECT_NAME = '{$PROJECT_NAME}';

{if $APPLICATION_THEME}
define('URL_THEME', URL_{$APPLICATION_CDN_CODE_UPPER} . '/{$APPLICATION_THEME}');
define('URL_THEME_IMAGES', URL_THEME . '/{$APPLICATION_THEME_IMAGES}');
{/if}