<?php
define('PATH_ROOT', dirname(__DIR__));
define('PATH_PROJECT', __DIR__);
define('PATH_CLASSES', PATH_PROJECT . DIRECTORY_SEPARATOR .  '{$PATH_CLASSES}' );
define('PATH_FILER', PATH_ROOT . DIRECTORY_SEPARATOR . '{$PATH_FILER}' );
define('PATH_CACHE', PATH_ROOT . DIRECTORY_SEPARATOR .  '{$PATH_CACHE}' );
define("ARCHITEKT_DATATABLE_PREFIX", '{$DATATABLE_PREFIX}' );

const EMAIL_SENDER_EMAIL = 'no-reply@mmo-str.com';
const EMAIL_SENDER_NAME = 'Exile';
